
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew coreutils
brew fish
brew fortune
brew fzf
brew gdbm
brew ghc
brew ghq
brew htop
brew libevent
brew libyaml
brew mas
brew openssl
brew pcre2
brew perl
brew pkg-config
brew pyenv
brew python
brew readline
brew reattach-to-user-namespace
brew rmtrash
brew ruby
brew sqlite
brew terraform
brew tmux
brew vim
brew xz

tap homebrew/boneyard

tap homebrew/cask-fonts
cask font-fontawesome

tap homebrew/cask-versions

tap homebrew/cask
cask docker
cask jad
cask karabiner-elements
cask ngrok
cask pgadmin4
cask pycharm
cask skype
cask sourcetree
cask vagrant-manager
cask vlc
cask xquartz

tap neovim/neovim

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask google-chrome
cask java
cask kindle
cask obs
cask postico
cask sequel-pro
cask slack
cask vagrant
cask virtualbox
cask wireshark

# App Store applications
appstore 682658836 GarageBand (10.3.0)
appstore 408981434 iMovie (10.1.9)
appstore 409183694 Keynote (8.1)
appstore 409203825 Numbers (5.1)
appstore 409201541 Pages (7.1)
